---
services:
  main:
    command: /usr/local/bin/start-container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - WAS_ADMINHOST_PORT=9060
      - WAS_DEFAULTHOST_PORT=9080
    image: registry.camunda.cloud/team-cambpm/camunda-ci-websphere:8.0-postgresql-9.1-port
    ports:
      - 5432/tcp
      - 9060/tcp
      - 9080/tcp
    restart: on-failure
version: '3'
