---
services:
  main:
    command: /usr/local/bin/start-container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment: []
    image: registry.camunda.cloud/team-cambpm/camunda-ci-oracle:11
    ports:
      - 1521/tcp
      - 22/tcp
    restart: on-failure
version: '3'
