---
services:
  main:
    command: /home/camunda/start_container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - CAM_LDAP_USERNAME=${CAM_LDAP_USERNAME}
      - CAM_LDAP_PASSWORD=${CAM_LDAP_PASSWORD}
      - CAMUNDA_VERSION=${CAMUNDA_VERSION}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    image: registry.camunda.com/camunda-ci-weblogic:12R2-oracle-18c-autosetup
    ports:
      - 7001/tcp
    restart: on-failure
version: '3'
