---
services:
  main:
    command: /home/camunda/start_container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    image: registry.camunda.com/camunda-ci-weblogic:12R2-oracle-18c-autosetup-7.12.0-alpha6
    ports:
      - 7001/tcp
    restart: on-failure
version: '3'
