---
services:
  main:
    command: /usr/local/bin/start-container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - TRANSACTION_ISOLATION_LEVEL=${TRANSACTION_ISOLATION_LEVEL:-REPEATABLE-READ}
    image: registry.camunda.cloud/team-cambpm/camunda-ci-mysql:5.7
    ports:
      - 3306/tcp
      - 22/tcp
    restart: on-failure
version: '3'
