---
services:
  main:
    command: /usr/local/bin/start-container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - profiles=${profiles}
      - version=${version}
      - nexus_pass=${nexus_pass}
    image: registry.camunda.cloud/team-cambpm/camunda-ci-weblogic:12R2-oracle-12
    ports:
      - 7001/tcp
      - 1521/tcp
      - 22/tcp
    restart: on-failure
version: '3'
